language: python
matrix:
  include:
    - python: "2.7"
      env: NUMPY=numpy
    - python: "3.4"
      env: NUMPY=numpy
    - python: "pypy"
      env: NUMPY="git+https://bitbucket.org/pypy/numpy.git"
# command to install dependencies and translate deap in py3k
install:
  - python setup.py install
  - pip install $NUMPY
  - if [[ ${TRAVIS_PYTHON_VERSION%%.*} == '3' ]]; then 2to3 --output-dir=py3k/deap -W -n deap; fi
# command to run tests
script:
  - if [[ ${TRAVIS_PYTHON_VERSION%%.*} == '3' ]]; then nosetests -v --where=py3k; else nosetests -v; fi