language: python
matrix:
  include:
    - python: "2.7"
      env: NUMPY=numpy
    - python: "3.4"
      env: NUMPY=numpy
    - python: "pypy"
      env: NUMPY="git+https://bitbucket.org/pypy/numpy.git"
# command to install dependencies and translate deap in py3k
install:
  - |
      if [ "$TRAVIS_PYTHON_VERSION" = "pypy" ]; then
        export PYENV_ROOT="$HOME/.pyenv"
        if [ -f "$PYENV_ROOT/bin/pyenv" ]; then
          cd "$PYENV_ROOT" && git pull
        else
          rm -rf "$PYENV_ROOT" && git clone --depth 1 https://github.com/yyuu/pyenv.git "$PYENV_ROOT"
        fi
        export PYPY_VERSION="4.0.1"
        "$PYENV_ROOT/bin/pyenv" install "pypy-$PYPY_VERSION"
        virtualenv --python="$PYENV_ROOT/versions/pypy-$PYPY_VERSION/bin/python" "$HOME/virtualenvs/pypy-$PYPY_VERSION"
        source "$HOME/virtualenvs/pypy-$PYPY_VERSION/bin/activate"
        NUMPY=$NUMPY"@pypy-4.0.1"
        pip install nose
      fi
  - python setup.py install
  - pip install $NUMPY
  
# command to run tests
script:
  - if [[ ${TRAVIS_PYTHON_VERSION%%.*} == '3' ]]; then python setup.py nosetests -v; else nosetests -v; fi
