language: python
matrix:
  include:
    - python: "2.7"
      env: NUMPY=numpy
    - python: "3.4"
      env: NUMPY=numpy
    - python: "pypy"
      env: NUMPY="git+https://bitbucket.org/pypy/numpy.git"
# command to install dependencies and translate deap in py3k
install:
  - python setup.py install
  - pip install $NUMPY
  - if [[ ${TRAVIS_PYTHON_VERSION%%.*} == '3' ]]; then 2to3 -w --output-dir=py3k -W -n deap; fi
# command to run tests
script:
  # run python3 tests from build/lib because the 2to3 from setup.py does not modify files in-place
  - nosetests -v