language: python
matrix:
  include:
    - python: "2.7"
      env: NUMPY=numpy
    - python: "3.4"
      env: NUMPY=numpy
    - python: "pypy"
      env: NUMPY="git+https://bitbucket.org/pypy/numpy.git"
# command to install dependencies
install:
  - python setup.py install
  - pip install $NUMPY
# command to run tests
script:
  # run python3 tests from build/lib because the 2to3 from setup.py does not modify files in-place
  - if [[ ${TRAVIS_PYTHON_VERSION%%.*} == '3' ]]; then nosetests -v --where=build/lib; else nosetests -v; fi