language: python
matrix:
  include:
    - python: "2.7"
      env: NUMPY=numpy
    - python: "3.4"
      env: NUMPY=numpy
    - python: "pypy"
      env: NUMPY="git+https://bitbucket.org/pypy/numpy.git"
# command to install dependencies
install:
  - python setup.py install
  - pip install $NUMPY
# command to run tests
script: nosetests 